name: mulesoft build


on:
  push: 
    branches: [master]

jobs: 
  build: 
    name: build application 
    runs-on: ubuntu-latest
    steps:
      - name: check out the code 
        uses: actions/checkout@v4
      - name: setup JDK 17
        uses: actions/setup-java@v4
        with: 
          java-version: "17"
          distribution: zulu
          cache: maven
          
      - name: package with maven
        run: mvn package --settings .github/settings.xml
        env: 
          CONNECTED_APP_CLIENT_ID: ${{ vars.CONNECTED_APP_CLIENT_ID}}
          CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
    
    